#table(
  columns: 1,
  stroke: none,
  align: (auto),
  table.header[#table.cell(stroke: (bottom: 1.2pt))[bytes]],
  [#table.cell(stroke: (bottom: 0.6pt))[0 B]],
  [#table.cell(stroke: (bottom: 0.6pt))[100 B]],
  [#table.cell(stroke: (bottom: 0.6pt))[1,000 B]],
  [#table.cell(stroke: (bottom: 0.6pt))[1 KiB]],
  [#table.cell(stroke: (bottom: 0.6pt))[976.6 KiB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1 MiB]],
  [#table.cell(stroke: (bottom: 0.6pt))[953.7 MiB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1 GiB]],
  [#table.cell(stroke: (bottom: 0.6pt))[931.3 GiB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1 TiB]],
  [#table.cell(stroke: (bottom: 0.6pt))[None]],
  [#table.cell(stroke: (bottom: 0.6pt))[-100 B]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1,000 B]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1 MiB]],
)
