#table(
  columns: 2,
  stroke: none,
  align: (auto, auto),
  table.header[#table.cell(stroke: (bottom: 1.2pt))[float]][#table.cell(stroke: (bottom: 1.2pt))[integer]],
  [#table.cell(stroke: (bottom: 0.6pt))[0]], [#table.cell(stroke: (bottom: 0.6pt))[0]],
  [#table.cell(stroke: (bottom: 0.6pt))[100.00]], [#table.cell(stroke: (bottom: 0.6pt))[100.00]],
  [#table.cell(stroke: (bottom: 0.6pt))[1.36]], [#table.cell(stroke: (bottom: 0.6pt))[1.00]],
  [#table.cell(stroke: (bottom: 0.6pt))[1.00]], [#table.cell(stroke: (bottom: 0.6pt))[113.53K]],
  [#table.cell(stroke: (bottom: 0.6pt))[10.00M]], [#table.cell(stroke: (bottom: 0.6pt))[10.00M]],
  [#table.cell(stroke: (bottom: 0.6pt))[100,000.00Q]], [#table.cell(stroke: (bottom: 0.6pt))[100.00Q]],
  [#table.cell(stroke: (bottom: 0.6pt))[0.00]], [#table.cell(stroke: (bottom: 0.6pt))[993.38M]],
  [#table.cell(stroke: (bottom: 0.6pt))[None]], [#table.cell(stroke: (bottom: 0.6pt))[None]],
  [#table.cell(stroke: (bottom: 0.6pt))[-10.00]], [#table.cell(stroke: (bottom: 0.6pt))[-10.00]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1.36]], [#table.cell(stroke: (bottom: 0.6pt))[-1.00]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1.00]], [#table.cell(stroke: (bottom: 0.6pt))[0]],
  [#table.cell(stroke: (bottom: 0.6pt))[-10.00M]], [#table.cell(stroke: (bottom: 0.6pt))[-10.00M]],
  [#table.cell(stroke: (bottom: 0.6pt))[nan]], [#table.cell(stroke: (bottom: 0.6pt))[-868.24K]],
  [#table.cell(stroke: (bottom: 0.6pt))[inf]], [#table.cell(stroke: (bottom: 0.6pt))[-342.52M]],
  [#table.cell(stroke: (bottom: 0.6pt))[-inf]], [#table.cell(stroke: (bottom: 0.6pt))[None]],
)
