#table(
  columns: 2,
  stroke: none,
  align: (auto, auto),
  table.header[#table.cell(stroke: (bottom: 1.2pt))[float]][#table.cell(stroke: (bottom: 1.2pt))[integer]],
  [#table.cell(stroke: (bottom: 0.6pt))[0]], [#table.cell(stroke: (bottom: 0.6pt))[0]],
  [#table.cell(stroke: (bottom: 0.6pt))[100]], [#table.cell(stroke: (bottom: 0.6pt))[100]],
  [#table.cell(stroke: (bottom: 0.6pt))[1.36]], [#table.cell(stroke: (bottom: 0.6pt))[1.00]],
  [#table.cell(stroke: (bottom: 0.6pt))[1.00]], [#table.cell(stroke: (bottom: 0.6pt))[114K]],
  [#table.cell(stroke: (bottom: 0.6pt))[10.0M]], [#table.cell(stroke: (bottom: 0.6pt))[10.0M]],
  [#table.cell(stroke: (bottom: 0.6pt))[100,000Q]], [#table.cell(stroke: (bottom: 0.6pt))[100Q]],
  [#table.cell(stroke: (bottom: 0.6pt))[0.000501]], [#table.cell(stroke: (bottom: 0.6pt))[993M]],
  [#table.cell(stroke: (bottom: 0.6pt))[None]], [#table.cell(stroke: (bottom: 0.6pt))[None]],
  [#table.cell(stroke: (bottom: 0.6pt))[-10.0]], [#table.cell(stroke: (bottom: 0.6pt))[-10.0]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1.36]], [#table.cell(stroke: (bottom: 0.6pt))[-1.00]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1.00]], [#table.cell(stroke: (bottom: 0.6pt))[0]],
  [#table.cell(stroke: (bottom: 0.6pt))[-10.0M]], [#table.cell(stroke: (bottom: 0.6pt))[-10.0M]],
  [#table.cell(stroke: (bottom: 0.6pt))[nan]], [#table.cell(stroke: (bottom: 0.6pt))[-868K]],
  [#table.cell(stroke: (bottom: 0.6pt))[inf]], [#table.cell(stroke: (bottom: 0.6pt))[-343M]],
  [#table.cell(stroke: (bottom: 0.6pt))[-inf]], [#table.cell(stroke: (bottom: 0.6pt))[None]],
)
