#table(
  columns: 2,
  stroke: none,
  align: (auto, auto),
  table.header[#table.cell(stroke: (bottom: 1.2pt))[float]][#table.cell(stroke: (bottom: 1.2pt))[integer]],
  [#table.cell(stroke: (bottom: 0.6pt))[0]], [#table.cell(stroke: (bottom: 0.6pt))[0]],
  [#table.cell(stroke: (bottom: 0.6pt))[100 #sym.times 10#super[0]]], [#table.cell(stroke: (bottom: 0.6pt))[100 #sym.times 10#super[0]]],
  [#table.cell(stroke: (bottom: 0.6pt))[1]], [#table.cell(stroke: (bottom: 0.6pt))[1]],
  [#table.cell(stroke: (bottom: 0.6pt))[1]], [#table.cell(stroke: (bottom: 0.6pt))[100 #sym.times 10#super[3]]],
  [#table.cell(stroke: (bottom: 0.6pt))[10 #sym.times 10#super[6]]], [#table.cell(stroke: (bottom: 0.6pt))[10 #sym.times 10#super[6]]],
  [#table.cell(stroke: (bottom: 0.6pt))[100 #sym.times 10#super[18]]], [#table.cell(stroke: (bottom: 0.6pt))[100 #sym.times 10#super[15]]],
  [#table.cell(stroke: (bottom: 0.6pt))[500 #sym.times 10#super[-6]]], [#table.cell(stroke: (bottom: 0.6pt))[1000 #sym.times 10#super[6]]],
  [#table.cell(stroke: (bottom: 0.6pt))[None]], [#table.cell(stroke: (bottom: 0.6pt))[None]],
  [#table.cell(stroke: (bottom: 0.6pt))[-10 #sym.times 10#super[0]]], [#table.cell(stroke: (bottom: 0.6pt))[-10 #sym.times 10#super[0]]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1]], [#table.cell(stroke: (bottom: 0.6pt))[-1]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1]], [#table.cell(stroke: (bottom: 0.6pt))[0]],
  [#table.cell(stroke: (bottom: 0.6pt))[-10 #sym.times 10#super[6]]], [#table.cell(stroke: (bottom: 0.6pt))[-10 #sym.times 10#super[6]]],
  [#table.cell(stroke: (bottom: 0.6pt))[nan]], [#table.cell(stroke: (bottom: 0.6pt))[-900 #sym.times 10#super[3]]],
  [#table.cell(stroke: (bottom: 0.6pt))[inf]], [#table.cell(stroke: (bottom: 0.6pt))[-300 #sym.times 10#super[6]]],
  [#table.cell(stroke: (bottom: 0.6pt))[-inf]], [#table.cell(stroke: (bottom: 0.6pt))[None]],
)
