#table(
  columns: 2,
  stroke: none,
  align: (auto, auto),
  table.header[#table.cell(stroke: (bottom: 1.2pt))[float]][#table.cell(stroke: (bottom: 1.2pt))[integer]],
  [#table.cell(stroke: (bottom: 0.6pt))[0.00]], [#table.cell(stroke: (bottom: 0.6pt))[0.00]],
  [#table.cell(stroke: (bottom: 0.6pt))[+1.00 #sym.times 10#super[+2]]], [#table.cell(stroke: (bottom: 0.6pt))[+1.00 #sym.times 10#super[+2]]],
  [#table.cell(stroke: (bottom: 0.6pt))[+1.36]], [#table.cell(stroke: (bottom: 0.6pt))[+1.00]],
  [#table.cell(stroke: (bottom: 0.6pt))[+1.00]], [#table.cell(stroke: (bottom: 0.6pt))[+1.14 #sym.times 10#super[+5]]],
  [#table.cell(stroke: (bottom: 0.6pt))[+1.00 #sym.times 10#super[+7]]], [#table.cell(stroke: (bottom: 0.6pt))[+1.00 #sym.times 10#super[+7]]],
  [#table.cell(stroke: (bottom: 0.6pt))[+1.00 #sym.times 10#super[+20]]], [#table.cell(stroke: (bottom: 0.6pt))[+1.00 #sym.times 10#super[+17]]],
  [#table.cell(stroke: (bottom: 0.6pt))[+5.01 #sym.times 10#super[-4]]], [#table.cell(stroke: (bottom: 0.6pt))[+9.93 #sym.times 10#super[+8]]],
  [#table.cell(stroke: (bottom: 0.6pt))[None]], [#table.cell(stroke: (bottom: 0.6pt))[None]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1.00 #sym.times 10#super[+1]]], [#table.cell(stroke: (bottom: 0.6pt))[-1.00 #sym.times 10#super[+1]]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1.36]], [#table.cell(stroke: (bottom: 0.6pt))[-1.00]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1.00]], [#table.cell(stroke: (bottom: 0.6pt))[0.00]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1.00 #sym.times 10#super[+7]]], [#table.cell(stroke: (bottom: 0.6pt))[-1.00 #sym.times 10#super[+7]]],
  [#table.cell(stroke: (bottom: 0.6pt))[nan]], [#table.cell(stroke: (bottom: 0.6pt))[-8.68 #sym.times 10#super[+5]]],
  [#table.cell(stroke: (bottom: 0.6pt))[inf]], [#table.cell(stroke: (bottom: 0.6pt))[-3.43 #sym.times 10#super[+8]]],
  [#table.cell(stroke: (bottom: 0.6pt))[-inf]], [#table.cell(stroke: (bottom: 0.6pt))[None]],
)
