#table(
  columns: 1,
  stroke: none,
  align: (auto),
  table.header[#table.cell(stroke: (bottom: 1.2pt))[bytes]],
  [#table.cell(stroke: (bottom: 0.6pt))[0 B]],
  [#table.cell(stroke: (bottom: 0.6pt))[+100 B]],
  [#table.cell(stroke: (bottom: 0.6pt))[+1 kB]],
  [#table.cell(stroke: (bottom: 0.6pt))[+1 kB]],
  [#table.cell(stroke: (bottom: 0.6pt))[+1 MB]],
  [#table.cell(stroke: (bottom: 0.6pt))[+1 MB]],
  [#table.cell(stroke: (bottom: 0.6pt))[+1 GB]],
  [#table.cell(stroke: (bottom: 0.6pt))[+1.1 GB]],
  [#table.cell(stroke: (bottom: 0.6pt))[+1 TB]],
  [#table.cell(stroke: (bottom: 0.6pt))[+1.1 TB]],
  [#table.cell(stroke: (bottom: 0.6pt))[None]],
  [#table.cell(stroke: (bottom: 0.6pt))[-100 B]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1 kB]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1 MB]],
)
