#table(
  columns: 1,
  stroke: none,
  align: (auto),
  table.header[#table.cell(stroke: (bottom: 1.2pt))[bytes]],
  [#table.cell(stroke: (bottom: 0.6pt))[0B]],
  [#table.cell(stroke: (bottom: 0.6pt))[100B]],
  [#table.cell(stroke: (bottom: 0.6pt))[1kB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1kB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1MB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1MB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1GB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1.1GB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1TB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1.1TB]],
  [#table.cell(stroke: (bottom: 0.6pt))[None]],
  [#table.cell(stroke: (bottom: 0.6pt))[-100B]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1kB]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1MB]],
)
