#table(
  columns: 1,
  stroke: none,
  align: (auto),
  table.header[#table.cell(stroke: (bottom: 1.2pt))[bytes]],
  [#table.cell(stroke: (bottom: 0.6pt))[0.00 B]],
  [#table.cell(stroke: (bottom: 0.6pt))[100 B]],
  [#table.cell(stroke: (bottom: 0.6pt))[1.00 kB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1.02 kB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1.00 MB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1.05 MB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1.00 GB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1.07 GB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1.00 TB]],
  [#table.cell(stroke: (bottom: 0.6pt))[1.10 TB]],
  [#table.cell(stroke: (bottom: 0.6pt))[None]],
  [#table.cell(stroke: (bottom: 0.6pt))[-100 B]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1.00 kB]],
  [#table.cell(stroke: (bottom: 0.6pt))[-1.05 MB]],
)
