#table(
  columns: 1,
  stroke: none,
  align: (auto),
  table.header(
    [\= Header]
  ),
table.hline(stroke: 1.2pt),
  [\#a],
  table.hline(stroke: 0.6pt),
  [Stuff \#Here],
  table.hline(stroke: 0.6pt),
  [That's a lot of \$],
  table.hline(stroke: 0.6pt),
  [Stuff\\Or],
  table.hline(stroke: 0.6pt),
  [A \<label\>],
  table.hline(stroke: 0.6pt),
  [\@reference],
  table.hline(stroke: 0.6pt),
  [Higher\~Lower],
  table.hline(stroke: 0.6pt),
  [yes\_no\_maybe],
  table.hline(stroke: 0.6pt),
  [hello^squared],
  table.hline(stroke: 0.6pt),
  [Stuff {Other}],
  table.hline(stroke: 0.6pt),
  [More (brackets)],
  table.hline(stroke: 0.6pt),
  [\*bold\*],
  table.hline(stroke: 0.6pt),
  [hello\*star],
  table.hline(stroke: 0.6pt),
  [\- list],
  table.hline(stroke: 0.6pt),
)
