#table(
  columns: 1,
  stroke: (x, y) => (
    bottom: if y < 1 { 1.2pt } else { 0.6pt },
    left: none,
    right: none,
    top: none
  ),
  align: (auto),
  table.header([\= Header]),
  [\#a],
  [Stuff \#Here],
  [That's a lot of \$],
  [Stuff\\Or],
  [A \<label\>],
  [\@reference],
  [Higher\~Lower],
  [yes\_no\_maybe],
  [hello^squared],
  [Stuff {Other}],
  [More (brackets)],
  [\*bold\*],
  [hello\*star],
  [\- list],
)
