#table(
  columns: 1,
  stroke: none,
  align: (auto),
  table.header[#table.cell(stroke: (bottom: 1.2pt))[\= Header]],
  [#table.cell(stroke: (bottom: 0.6pt))[\#a]],
  [#table.cell(stroke: (bottom: 0.6pt))[Stuff \#Here]],
  [#table.cell(stroke: (bottom: 0.6pt))[That's a lot of \$]],
  [#table.cell(stroke: (bottom: 0.6pt))[Stuff\\Or]],
  [#table.cell(stroke: (bottom: 0.6pt))[A \<label\>]],
  [#table.cell(stroke: (bottom: 0.6pt))[\@reference]],
  [#table.cell(stroke: (bottom: 0.6pt))[Higher\~Lower]],
  [#table.cell(stroke: (bottom: 0.6pt))[yes\_no\_maybe]],
  [#table.cell(stroke: (bottom: 0.6pt))[hello^squared]],
  [#table.cell(stroke: (bottom: 0.6pt))[Stuff {Other}]],
  [#table.cell(stroke: (bottom: 0.6pt))[More (brackets)]],
  [#table.cell(stroke: (bottom: 0.6pt))[\*bold\*]],
  [#table.cell(stroke: (bottom: 0.6pt))[hello\*star]],
  [#table.cell(stroke: (bottom: 0.6pt))[\- list]],
)
