name: CI

env:
  MINIMUM_PYTHON: "3.11"

on:
  push:
    branches:
      - master
    tags:
      - "**"
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
        with:
          args: check

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/ruff-action@v3
        with:
          args: format

  typing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.8"

      - name: Set up Python
        run: uv python install ${{ matrix.python}}

      - name: Run type check
        run: |
          uv run pyrefly check src/ tests/ --config pyproject.toml --output-format=github

  test:
    name: test py${{ matrix.python }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python: [ 3.11, 3.12, 3.13, 3.14 ]

    env:
      PYTHON: ${{ matrix.python }}
      OS: ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          # Install a specific version of uv.
          version: "0.11.8"

      - name: Set up Python
        run: uv python install ${{ matrix.python}}

      - name: Install the project
        run: uv sync --group test --no-dev --all-extras

      - name: Run tests
        run: COV_CORE_SOURCE=src COV_CORE_CONFIG=pyproject.toml
          COV_CORE_DATAFILE=.coverage.eager uv run --no-sync pytest tests/

      - name: Deal with coverage
        run: |
          uv run --no-sync coverage html --skip-covered --skip-empty
          uv run --no-sync coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
          uv run --no-sync coverage report --fail-under=100

      - name: Upload HTML report if check failed.
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: htmlcov
        if: ${{ failure() }}

      - name: Install the project with highest bounds
        run: uv sync --resolution highest --group test --no-dev --all-extras

      - name: Run tests again
        run: uv run --no-sync pytest tests/
